# Server Port
server.port=8084

# Application Name
spring.application.name=department-service

# Load secrets from hidden .env file (if it exists)
spring.config.import=optional:file:.env[.properties]

# Neon.tech PostgreSQL Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Other Services URLs (through API Gateway)
doctor.service.url=http://localhost:8080/doctors

spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=45000
